# 
FROM python:3.10.8-slim-buster

# 
WORKDIR /code

# 
COPY ./requirements.txt /code/requirements.txt

#
# ARG TARGET_ENV
# ENV ENVIRONMENT=$TARGET_ENV
COPY ./.env /code/.env
COPY ./.env.* /code/

# 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# 
COPY ./app /code/app

# 
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
